<?php
// $Id$

/**
 * @file
 * Franko payment method.
 *
 * @author Mike Gogulski - http://www.nostate.com/ http://www.gogulski.com/
 */
//variable_set('uc_payment_logging', TRUE);

/**
 * Set up the Franko payment method settings form.
 */
function uc_franko_settings_form() {
  $form = array();

  $form['server'] = array(
    '#type' => 'fieldset',
    '#title' => t('Server settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['server']['uc_franko_server_scheme'] = array(
    '#type' => 'radios',
    '#title' => t('Server scheme'),
    '#default_value' => variable_get('uc_franko_server_scheme', 1),
    '#options' => array('http' => 'HTTP', 'https' => 'HTTPS'),
  );
  $form['server']['uc_franko_server_certificate_path'] = array(
    '#type' => 'textfield',
    '#title' => t('SSL certificate path'),
    '#default_value' => variable_get('uc_franko_server_certificate_path', ''),
    '#description' => t('Location of the server.cert file you generated for frankod, if you are using HTTPS'),
  );
  $form['server']['uc_franko_server_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Server username'),
    '#default_value' => variable_get('uc_franko_server_username', ''),
    '#description' => t("User name for your Franko server's JSON-RPC-HTTP interface"),
  );
  $form['server']['uc_franko_server_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Server password'),
    '#default_value' => variable_get('uc_franko_server_password', ''),
    '#description' => t('Franko server password'),
  );
  $form['server']['uc_franko_server_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Server hostname'),
    '#default_value' => variable_get('uc_franko_server_address', 'localhost'),
    '#description' => t('Franko server domain name or IP address. Use "localhost" if frankod is running on the Ubercart server.'),
  );
  $form['server']['uc_franko_server_port'] = array(
    '#type' => 'textfield',
    '#title' => t('Server port'),
    '#default_value' => variable_get('uc_franko_server_port', '7912'),
    '#description' => t('Franko server port (generally 7912)'),
  );
  $form['transaction'] = array(
    '#type' => 'fieldset',
    '#title' => t('Transaction settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['transaction']['uc_franko_transaction_timeout'] = array(
    '#type' => 'textfield',
    '#title' => t('Transaction timeout (hours)'),
    '#default_value' => variable_get('uc_franko_transaction_timeout', '72'),
    '#description' => t('Transactions not paid for within this number of hours will be automatically cancelled. Decimals are permitted.'),
  );
  $form['transaction']['uc_franko_transaction_confirms'] = array(
    '#type' => 'textfield',
    '#title' => t('Transaction confirmations'),
    '#default_value' => variable_get('uc_franko_transaction_confirms', '1'),
    '#description' => t('Minimum number of Franko transaction network confirmations required before a payment is considered accepted.'),
  );
  $form['donate'] = array(
    '#type' => 'item',
    '#title' => t('Like this plugin? Your gift of Frankos to FE35Ez4oq8jVfEaKJAHTugkkwzVVhuLxVZ would be greatly appreciated. Thank you!'),
  );
  return system_settings_form($form);
}

/**
 * Validate Franko payment method settings.
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function uc_payment_methods_form_validate($form, &$form_state) {
  $c = $form_state['values']['uc_franko_server_scheme'];
  if ($c != 'http' && $c != 'https')
    form_set_error('uc_franko_server_scheme', t('Server scheme must be HTTP or HTTPS.'));
  if ($c == 'https') {
    $c = $form_state['values']['uc_franko_server_certificate_path'];
    if (!empty($c) && !is_readable($c))
      form_set_error('uc_franko_server_certificate_path', t('SSL certificate file unreadable. Try using an absolute path.'));
  }
  $c = $form_state['values']['uc_franko_server_username'];
  if (empty($c))
    form_set_error('uc_franko_server_username', t('Server username is required.'));
  $c = $form_state['values']['uc_franko_server_password'];
  if (empty($c))
    form_set_error('uc_franko_server_password', t('Server password is required.'));
  $c = $form_state['values']['uc_franko_server_address'];
  if (empty($c))
    form_set_error('uc_franko_server_address', t('Server hostname is required.'));
  $c = $form_state['values']['uc_franko_server_port'];
  if (empty($c) || !is_numeric($c) || $c < 0 || $c > 65535 || floatval($c) != intval($c))
    form_set_error('uc_franko_server_port', t('Server port must be an integer and between 0 and 65535.'));
  $c = $form_state['values']['uc_franko_transaction_timeout'];
  if (empty($c) || !is_numeric($c) || $c <= 0)
    form_set_error('uc_franko_transaction_timeout', t('Transaction timeout must be greater than zero.'));
  $c = $form_state['values']['uc_franko_transaction_confirms'];
  if (!is_numeric($c) || $c < 0 || floatval($c) != intval($c))
    form_set_error('uc_franko_transaction_confirms', t('Required transaction confirmations must be an integer greater than or equal to zero.'));
}

/*******************************************************************************
 * Hook Functions (Ubercart)
 ******************************************************************************/

/**
 * Implementation of hook_mail_alter().
 * @param array $&message
 * @todo Make this less fragile.
 *
 * The idea here is to transform:
 *
 *   (t('Payment Method:'))(not 'Franko')'Franko'
 *
 * to
 *
 *   \1\2Franko -- send payment to...
 *
 * But only for invoice emails.
 */
function uc_franko_mail_alter(&$message) {
  if ($message['id'] == 'uc_order_action-mail' && !strstr(uc_store_email_from(), $message['to'])) {
    // fragile
    $bits = explode(" ", $_SESSION['messages']['status'][0]);
    $address = trim($bits[count($bits) - 1], ' .');
    // also looks fragile, no idea if it's really t()-safe
    $message['body'] = preg_replace('/(' . t('Payment Method:') . ')(.*)Franko/s',
      '${1}${2}Franko (' . t("send payment to Franko address !address.", array("!address" => $address)) . ')',
      $message['body']);
  }
}

/**
 * Implementation of hook_order().
 */
function uc_franko_order($op, &$arg1, $arg2) {
  switch ($op) {
    case 'submit':
      include_once("../uc_bitcoin/franko.inc");
      $franko_client = new FrankoClient(variable_get("uc_franko_server_scheme", ""),
        variable_get("uc_franko_server_username", ""),
        variable_get("uc_franko_server_password", ""),
        variable_get("uc_franko_server_address", ""),
        variable_get("uc_franko_server_port", ""),
        variable_get("uc_franko_server_certificate_path", ""));
      if (TRUE !== ($fault = $franko_client->can_connect())) {
        watchdog('uc_franko_order', 'Unable to access Franko server. Fault: !fault', $fault);
        return array(array(
          'pass' => FALSE,
          'message' => t('The Franko server is presently unavailable. Please contact the site administrator.')));
      }
      // stuff the order id, the total order price and a timestamp into the franko address's label
      $label = $arg1->order_id . " " . number_format($arg1->order_total, 2, ".", "") . " " . time();
      try {
        $address = $franko_client->query("getnewaddress", $label);
      } catch (FrankoClientException $e) {
        watchdog('uc_franko_order', 'getnewaddress failed. Fault: !fault', $e->getMessage());
        return array(array('pass' => FALSE, 'message' => t('The Franko server is presently unavailable. Please contact the site administrator.')));
      }
      if (!Franko::checkAddress($address))
        return array(array(
          'pass' => FALSE,
          'message' => t('The Franko server returned an invalid address. Please contact the site administrator.')));
      db_query("INSERT INTO {uc_payment_franko} (order_id, franko_address) VALUES (%d, '%s')", $arg1->order_id, $address);
      $message = t('Please send your payment of FRK @total to Franko address @address.', array(
        '@address' => $address,
        '@total' => $arg1->order_total));
      return array(array(
        'pass' => TRUE,
        'message' => $message));
      break;
  }
}

/**
 * Implementation of hook_payment_method().
 */
function uc_franko_payment_method() {
  $methods[] = array(
    'id' => 'franko',
    'name' => t('Franko'),
    'title' => t('Franko'),
    'desc' => t('Pay with Franko.'),
    'callback' => 'uc_payment_method_franko',
    'weight' => 1,
    'checkout' => TRUE,
    'no_gateway' => TRUE
  );
  return $methods;
}

/**
 * Implementation of hook_theme().
 */
function uc_franko_theme($existing, $type, $theme, $path) {
  return array(
    'uc_payment_method_' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/*******************************************************************************
 * Callback Functions, Forms, and Tables
 ******************************************************************************/

function uc_payment_method_franko($op, &$arg1) {
  switch ($op) {
      // Display the Franko address in the payment order pane.
      case 'customer-view':
    case 'order-view':
      $address = db_result(db_query("SELECT franko_address FROM {uc_payment_franko} WHERE order_id=%d", $arg1->order_id));
      return t('Franko address for payment: !address', array('!address' => $address));
      // Add Franko settings to the payment methods settings form.
      case 'settings':
      return uc_franko_settings_form();
  }
}

/*******************************************************************************
 * Franko functions and utility functions
 ******************************************************************************/

/**
 * Check for and try to process pending Franko transactions.
 */
function uc_franko_cron() {
  // TODO: Figure out how to handle user-modified order statuses
  $result = db_query("SELECT {uc_orders}.order_id,order_total,franko_address FROM {uc_orders} LEFT JOIN {uc_payment_franko} ON {uc_orders}.order_id={uc_payment_franko}.order_id WHERE payment_method='franko' and order_status='pending'");
  // TODO: test if $result has any rows

  // prepare the JSON-RPC client
  include_once("../uc_bitcoin/franko.inc");
  $franko_client = new FrankoClient(variable_get("uc_franko_server_scheme", ""),
    variable_get("uc_franko_server_username", ""),
    variable_get("uc_franko_server_password", ""),
    variable_get("uc_franko_server_address", ""),
    variable_get("uc_franko_server_port", ""),
    variable_get("uc_franko_server_certificate_path", ""));
  if (TRUE !== ($fault = $franko_client->can_connect()))
    return watchdog('uc_franko_cron', 'Unable to access Franko server. Fault: !fault', $fault);
  // loop through the open transactions
  while ($my_order = db_fetch_object($result)) {
    // check for transaction completion
    $address = $my_order->franko_address;
    try {
      $paid = $franko_client->query("getreceivedbyaddress", $address, variable_get("uc_franko_transaction_confirms", 1));
    } catch (FrankoClientException $e) {
      return watchdog('uc_franko', "Franko server communication failed on getreceivedbyaddress !address with fault string !fault", array("!address" => $address, '!fault' => $e->getMessage()), WATCHDOG_ALERT);
    }
    $order_id = $my_order->order_id;
    $order = uc_order_load($order_id);
    $order_balance = uc_payment_balance($order);
    $order_total = $my_order->order_total;
    // TODO: Handle overpayment
    // if the amount paid has changed, log a payment
    if ($order_total != $paid + $order_balance)
      uc_payment_enter($order_id, "franko", $paid - ($order_total - $order_balance), 0, NULL, '');

    if ($paid >= $order_total) {
      // PAID IN FULL
      // TODO: If the product was a downloadable, mark the order as completed
      // TODO: next line not needed since we're using uc_payment_enter?
      //uc_order_update_status($order_id, "payment_received");
      uc_order_comment_save($order_id, 9999999, t('Paid in full'), 'order', 'payment_received', TRUE);
      ca_pull_trigger('uc_order_status_email_update', $order);
      continue;
    }
    // NOT PAID YET
    try {
      $label = $franko_client->query("getlabel", $address);
    } catch (FrankoClientException $e) {
      return watchdog('uc_franko', "Franko server failed on getlabel for !address with fault string !fault", array("!address" => $address, '!fault' => $e->getMessage()), WATCHDOG_ALERT);
    }
    list($junk, $junk1, $timestamp) = explode(" ", $label);
    if (time() > ($timestamp + intval(floatval(variable_get("uc_franko_transaction_timeout", 72) * 60 * 60)))) {
      // ORDER EXPIRED
      // TODO: Handle refund of partial payment
      uc_order_update_status($order_id, "canceled");
      $cancelmsg = t("Your payment was not completed with at least !confirms within !timeout hours. Your order has been cancelled. If you have made a partial payment, please contact the shop administrator for a refund.", array(
        '!confirms' => format_plural(variable_get("uc_franko_transaction_confirms", 1), "one confirmation", "@count confirmations"),
        '!timeout' => variable_get("uc_franko_transaction_timeout", 72),
      ));
      uc_order_comment_save($my_order->order_id, 9999999, $cancelmsg, 'order', 'canceled', TRUE);
      ca_pull_trigger('uc_order_status_email_update', $order);
    }
  }
}
